#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: distutils3
# autospec version: v2
# autospec commit: f032afc
#
Name     : sos
Version  : 4.6.0
Release  : 46
URL      : https://github.com/sosreport/sos/archive/4.6.0/sos-4.6.0.tar.gz
Source0  : https://github.com/sosreport/sos/archive/4.6.0/sos-4.6.0.tar.gz
Summary  : Script of Scripts (SoS): an interactive, cross-platform, and cross-language workflow system for reproducible data analysis
Group    : Development/Tools
License  : GPL-2.0 GPL-2.0+
Requires: sos-bin = %{version}-%{release}
Requires: sos-data = %{version}-%{release}
Requires: sos-license = %{version}-%{release}
Requires: sos-man = %{version}-%{release}
Requires: sos-python = %{version}-%{release}
Requires: sos-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pypi(coverage)
BuildRequires : pypi(pexpect)
BuildRequires : pypi(pycodestyle)
BuildRequires : pypi(pyyaml)
BuildRequires : pypi(setuptools)
BuildRequires : pypi(sphinx)
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
Sos is a set of tools that gathers information about system
hardware and configuration. The information can then be used for
diagnostic purposes and debugging. Sos is commonly used to help
support technicians and developers.

%package bin
Summary: bin components for the sos package.
Group: Binaries
Requires: sos-data = %{version}-%{release}
Requires: sos-license = %{version}-%{release}

%description bin
bin components for the sos package.


%package data
Summary: data components for the sos package.
Group: Data

%description data
data components for the sos package.


%package doc
Summary: doc components for the sos package.
Group: Documentation
Requires: sos-man = %{version}-%{release}

%description doc
doc components for the sos package.


%package license
Summary: license components for the sos package.
Group: Default

%description license
license components for the sos package.


%package man
Summary: man components for the sos package.
Group: Default

%description man
man components for the sos package.


%package python
Summary: python components for the sos package.
Group: Default
Requires: sos-python3 = %{version}-%{release}

%description python
python components for the sos package.


%package python3
Summary: python3 components for the sos package.
Group: Default
Requires: python3-core
Provides: pypi(sos)
Requires: pypi(coverage)
Requires: pypi(fasteners)
Requires: pypi(jinja2)
Requires: pypi(nbformat)
Requires: pypi(networkx)
Requires: pypi(pexpect)
Requires: pypi(psutil)
Requires: pypi(ptyprocess)
Requires: pypi(pycodestyle)
Requires: pypi(pydot)
Requires: pypi(pydotplus)
Requires: pypi(pygments)
Requires: pypi(pyyaml)
Requires: pypi(pyzmq)
Requires: pypi(setuptools)
Requires: pypi(six)
Requires: pypi(sphinx)
Requires: pypi(tqdm)

%description python3
python3 components for the sos package.


%prep
%setup -q -n sos-4.6.0
cd %{_builddir}/sos-4.6.0
pushd ..
cp -a sos-4.6.0 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1697573909
export GCC_IGNORE_WERROR=1
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

pushd ../buildavx2/
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -m64 -march=x86-64-v3 "
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS -m64 -march=x86-64-v3 "
python3 setup.py build

popd
%install
export GCC_IGNORE_WERROR=1
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -fdebug-types-section -femit-struct-debug-baseonly -fno-lto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/sos
cp %{_builddir}/sos-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/sos/1f199f2dcc0341653fc919334d9c26d0d2098f93 || :
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----
pushd ../buildavx2/
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -m64 -march=x86-64-v3 "
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS -m64 -march=x86-64-v3 "
python3 -tt setup.py build install --root=%{buildroot}-v3
popd
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/config/sos.conf
/usr/config/tmpfilesd-sos-rh.conf

%files bin
%defattr(-,root,root,-)
/usr/bin/sos
/usr/bin/sos-collector
/usr/bin/sosreport

%files data
%defattr(-,root,root,-)
/usr/share/licenses/sos/LICENSE

%files doc
%defattr(0644,root,root,0755)
/usr/share/doc/sos/*

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/sos/1f199f2dcc0341653fc919334d9c26d0d2098f93

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/sos-clean.1
/usr/share/man/man1/sos-collect.1
/usr/share/man/man1/sos-collector.1
/usr/share/man/man1/sos-help.1
/usr/share/man/man1/sos-mask.1
/usr/share/man/man1/sos-report.1
/usr/share/man/man1/sos.1
/usr/share/man/man1/sosreport.1
/usr/share/man/man5/sos.conf.5

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
